%%%%%%%%%%%%%%
%%automatically generated by script

%%%%%%%%%%%%%%
%%build the loop topology based on optimized graph
clear;
warning('off');
open_system('adc_test');

%%%%%%%%%%%%%%
%%writing the simulation settings
t0=clock;
bw=22050.0;
Temp=297;
k=1.38e-23;
R=1024;
Fs=45158400.0;
Ts=2.2144274376417234e-08;
N=32768;
nper=5;
delta=0;
finrad=43295.073757284335;
alfa=0.9999;
Fin=6890.625;
Ampl=0.9;
Ntransient=50;
NCOMPARATORI=15;
Cs=2.5e-12;
Amax=1000;
sr=2000000000000.0;
match=1e-13;
options=simset('InitialState', zeros(1,5), 'RelTol', 1e-3, 'MaxStep', 1/Fs);
sim('adc_test', (N+Ntransient)/Fs, options);
w=hann_pv(N);
f=Fin/Fs;
fB=N*(bw/Fs);
yy1=zeros(1,N);
yy1=yout(2+Ntransient:1+N+Ntransient)';
ptot=zeros(1,N);
[snr,ptot]=calcSNR(yy1(1:N),f,1,fB,w,N);
Rbit=(snr-1.76)/6.02;
integrator_constr_1=max(abs(integrators_out_1));
integrator_constr_2=max(abs(integrators_out_2));
integrator_constr_3=max(abs(integrators_out_3));
integrator_constr_4=max(abs(integrators_out_4));
fileID = fopen('sim_res.txt','w');
fprintf(fileID,'%1.3f %1.3f %1.3f %1.3f %1.3f %1.3f\n',snr,Rbit,integrator_constr_1,integrator_constr_2,integrator_constr_3,integrator_constr_4);
fclose(fileID);
close_system('adc_test',1);
